#!/usr/bin/env python3
"""
Run once to embed local assets as base64 data URLs inside assets.js.
After running, index.html works by double-clicking — no server needed.

Usage:
    python3 embed_assets.py
"""
import base64, os, sys

def encode(path, mime):
    if not os.path.exists(path):
        print(f"ERROR: {path} not found", file=sys.stderr)
        sys.exit(1)
    with open(path, 'rb') as f:
        b64 = base64.b64encode(f.read()).decode('ascii')
    return f"data:{mime};base64,{b64}"

earth_url = encode('Earth_Blue_Marble.jpg', 'image/jpeg')
glb_url   = encode('x-37b.glb',            'model/gltf-binary')

with open('assets.js', 'w') as f:
    f.write('// Auto-generated by embed_assets.py — do not edit manually\n')
    f.write(f'window.EARTH_DATA_URL = "{earth_url}";\n')
    f.write(f'window.GLB_DATA_URL   = "{glb_url}";\n')

print(f"assets.js written successfully")
print(f"  Earth texture : {len(earth_url) // 1024:,} KB (base64)")
print(f"  GLB model     : {len(glb_url)   // 1024:,} KB (base64)")
print(f"\nOpen index.html directly in your browser — no server required.")
